CREATE TABLE IF NOT EXISTS CURATED.CUR_REVENUE_EGI_NRT
(
    -- Business & data columns
    r_revenue_egi_nrt_id BIGINT,
    fiscal_quarter VARCHAR(100),
    eg_net_revenue NUMERIC(18,4),
    region VARCHAR(100),
    region_id INTEGER,
    sales_order_identifier VARCHAR(100),
    sales_order_line_item_number VARCHAR(100),
    sap_order_key VARCHAR(100),
    order_create_calendar_date DATE,
    shipment_date DATE,
    eg_end_customer_name VARCHAR(500),
    final_rtm VARCHAR(100),
    secured_position_net_usd NUMERIC(18,4),
    sc_bklg_catg VARCHAR(100),
    sku_description VARCHAR(500),
    include_exclude VARCHAR(100),
    business_area_code VARCHAR(100),
    customer_po_number VARCHAR(500),
    financial_close_calendar_year_month_code VARCHAR(500),
    order_type VARCHAR(500),
    profit_center_hierarchy_level_3_description VARCHAR(500),
    profit_center_hierarchy_level_4_description VARCHAR(500),
    route_to_market VARCHAR(500),
    sales_order_completion_status_code VARCHAR(500),
    material_number VARCHAR(500),
    source_type VARCHAR(500),
    sum_of_base_quantity NUMERIC(18,4),
    sum_of_cp_unit_quantity NUMERIC(18,4),
    sum_of_cp_enterprise_standard_cost_usd NUMERIC(18,4),
    sum_of_cp_factory_margin_usd NUMERIC(18,4),
    sum_of_cp_gross_margin_usd NUMERIC(18,4),
    sum_of_cp_gross_revenue_usd NUMERIC(18,4),
    sum_of_cp_total_cost_of_sales_usd NUMERIC(18,4),
    sum_of_gross_revenue_usd NUMERIC(18,4),
    sum_of_net_revenue NUMERIC(18,4),
    sum_of_order_item_net_value_usd NUMERIC(18,4),
    sold_to_customer_sta VARCHAR(500),
    ship_to_customer_sta VARCHAR(500),
    cp_backlog_sni_revenue VARCHAR(100),
    delivery_identifier VARCHAR(100),
    sum_of_sales_order_base_quantity NUMERIC(30,15),
    sum_of_order_item_net_value_document_currency NUMERIC(30,15),
    start_date DATE,
    end_date DATE,
    batch_run_dt DATE,
    source_nm VARCHAR(500),
    created_by VARCHAR(500),
    create_dt TIMESTAMP WITHOUT TIME ZONE,
    last_update_dt TIMESTAMP WITHOUT TIME ZONE,
    process_timestamp TIMESTAMP WITHOUT TIME ZONE,
    -- Columns for CDC/SCD2 merge
    hash_key VARCHAR(64),
    watermark TIMESTAMP WITHOUT TIME ZONE,
    source_file VARCHAR(500), -- optional, for lineage
    ingestion_ts TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP -- optional, for audit
)
DISTSTYLE EVEN;

ALTER TABLE curated.cur_revenue_egi_nrt owner to arubauser;