CREATE TABLE IF NOT EXISTS published.dly_cust_flflm_bcklg_snapshot_nrt
(
	src_sys_typ VARCHAR(25)   ENCODE lzo
	,src_sys_nm VARCHAR(50)   ENCODE lzo
	,src_sys_rgn VARCHAR(25)   ENCODE lzo
	,rgn VARCHAR(25)   ENCODE lzo
	,sub_rgn VARCHAR(100)   ENCODE lzo
	,dcmt_src VARCHAR(25)   ENCODE lzo
	,dcmt_crt_dt DATE   ENCODE az64
	,dcmt_typ VARCHAR(10)   ENCODE lzo
	,dcmt_typ_dn VARCHAR(100)   ENCODE lzo
	,dcmt_id VARCHAR(25)   ENCODE lzo
	,dcmt_ln_itm VARCHAR(25)   ENCODE lzo
	,dcmt_crt_by VARCHAR(25)   ENCODE lzo
	,dcmt_age_dys INTEGER   ENCODE az64
	,cln_itm_age_dys INTEGER   ENCODE az64
	,dcmt_ln_itm_crt_dt DATE   ENCODE az64
	,rptg_prod_id VARCHAR(50)   ENCODE lzo
	,prod_id VARCHAR(50)   ENCODE lzo
	,prod_dn VARCHAR(250)   ENCODE lzo
	,prod_bs VARCHAR(50)   ENCODE lzo
	,prod_opt_drvd VARCHAR(25)   ENCODE lzo
	,prod_opt_src VARCHAR(25)   ENCODE lzo
	,prod_left5_ky VARCHAR(25)   ENCODE lzo
	,prod_typ VARCHAR(25)   ENCODE lzo
	,prod_grp VARCHAR(100)   ENCODE lzo
	,prod_fmly VARCHAR(100)   ENCODE lzo
	,bsn_cgy VARCHAR(100)   ENCODE lzo
	,prod_ras VARCHAR(100)   ENCODE lzo
	,pl VARCHAR(10)   ENCODE lzo
	,pl_dn VARCHAR(100)   ENCODE lzo
	,mtrl_mstr_pl VARCHAR(10)   ENCODE lzo
	,mtrl_mstr_pl_dn VARCHAR(100)   ENCODE lzo
	,ord_qty INTEGER   ENCODE az64
	,opn_qty INTEGER   ENCODE az64
	,po_qty INTEGER   ENCODE az64
	,po_opn_qty INTEGER   ENCODE az64
	,nt_invc_amt NUMERIC(28,4)   ENCODE az64
	,aup_unt_amt NUMERIC(28,4)   ENCODE az64
	,bcklg_aup_amt NUMERIC(28,4)   ENCODE az64
	,eg_nt_amt NUMERIC(28,4)   ENCODE az64
	,rptg_eg_nt_amt NUMERIC(28,4)   ENCODE az64
	,rptg_eg_nt_dtrmn VARCHAR(30)   ENCODE lzo
	,ord_typ_clsfn VARCHAR(50)   ENCODE lzo
	,dmnd_sub_typ_2 VARCHAR(50)   ENCODE lzo
	,dcmt_rvn_flg VARCHAR(5)   ENCODE lzo
	,hdr_stts VARCHAR(250)   ENCODE lzo
	,itm_stts VARCHAR(250)   ENCODE lzo
	,sls_plnt_cd VARCHAR(25)   ENCODE lzo
	,fctry_plnt_cd VARCHAR(25)   ENCODE lzo
	,splyr_plnt_cd VARCHAR(25)   ENCODE lzo
	,cc_plnt_cd VARCHAR(25)   ENCODE lzo
	,sldto_prty_id VARCHAR(50)   ENCODE lzo
	,sldto_prty_nm VARCHAR(250)   ENCODE lzo
	,sldto_ctry_cd VARCHAR(25)   ENCODE lzo
	,shpto_prty_nm VARCHAR(250)   ENCODE lzo
	,shpto_str_nm VARCHAR(250)   ENCODE lzo
	,shpto_cty_nm VARCHAR(250)   ENCODE lzo
	,shpto_st_cd VARCHAR(25)   ENCODE lzo
	,shpto_ctry_cd VARCHAR(25)   ENCODE lzo
	,shpto_ctry_nm VARCHAR(250)   ENCODE lzo
	,shpto_rgn_nm VARCHAR(250)   ENCODE lzo
	,shpto_sub_rgn_nm VARCHAR(250)   ENCODE lzo
	,end_usr_nm VARCHAR(250)   ENCODE lzo
	,end_usr_ctry_cd VARCHAR(25)   ENCODE lzo
	,rsllr_nm VARCHAR(250)   ENCODE lzo
	,rsllr_ctry_cd VARCHAR(25)   ENCODE lzo
	,dlvry_id VARCHAR(50)   ENCODE lzo
	,sls_org VARCHAR(25)   ENCODE lzo
	,rcvd_dt DATE   ENCODE az64
	,cust_rqstd_dlvry_dt DATE   ENCODE az64
	,cust_rqstd_shp_dt DATE   ENCODE az64
	,plnd_dlvry_dt DATE   ENCODE az64
	,frst_plnd_dlvry_dt DATE   ENCODE az64
	,inv_dt DATE   ENCODE az64
	,estmd_inv_dt DATE   ENCODE az64
	,shpg_pnt VARCHAR(25)   ENCODE lzo
	,hli VARCHAR(25)   ENCODE lzo
	,itm_cgy VARCHAR(25)   ENCODE lzo
	,ord_rsn_cd VARCHAR(25)   ENCODE lzo
	,sls_ofc_nm VARCHAR(25)   ENCODE lzo
	,prjct_flg VARCHAR(5)   ENCODE lzo
	,cust_po_id VARCHAR(80)   ENCODE lzo
	,splyr_po_id VARCHAR(25)   ENCODE lzo
	,splyr_po_ln_itm VARCHAR(25)   ENCODE lzo
	,splyr_po_ack_dt DATE   ENCODE az64
	,splyr_po_dt DATE   ENCODE az64
	,hub_flg VARCHAR(5)   ENCODE lzo
	,sls_rgn VARCHAR(25)   ENCODE lzo
	,deal_id VARCHAR(25)   ENCODE lzo
	,cust_ord_qt VARCHAR(50)   ENCODE lzo
	,shpg_pnt_flflm VARCHAR(25)   ENCODE lzo
	,shpfrm_rgn VARCHAR(25)   ENCODE lzo
	,rvn_ord VARCHAR(50)   ENCODE lzo
	,flw_typ VARCHAR(80)   ENCODE lzo
	,flw_sub_typ VARCHAR(50)   ENCODE lzo
	,b2b_ky VARCHAR(25)   ENCODE lzo
	,b2b_flg VARCHAR(5)   ENCODE lzo
	,b2b_cust_po_id VARCHAR(50)   ENCODE lzo
	,b2b_so_id VARCHAR(25)   ENCODE lzo
	,b2b_so_ln_itm VARCHAR(25)   ENCODE lzo
	,b2b_hdr_stts VARCHAR(250)   ENCODE lzo
	,b2b_itm_stts VARCHAR(250)   ENCODE lzo
	,b2b_sldto_ctry_cd VARCHAR(25)   ENCODE lzo
	,b2b_shpto_ctry_cd VARCHAR(25)   ENCODE lzo
	,b2b_end_usr_ctry_cd VARCHAR(25)   ENCODE lzo
	,b2b_splyr_po_id VARCHAR(25)   ENCODE lzo
	,b2b_so_usd_amt NUMERIC(28,4)   ENCODE az64
	,lgcy_ky VARCHAR(50)   ENCODE lzo
	,lgcy_ord_id VARCHAR(25)   ENCODE lzo
	,lgcy_ord_ln_itm VARCHAR(25)   ENCODE lzo
	,atp_flg VARCHAR(5)   ENCODE lzo
	,least_itm_stts VARCHAR(250)   ENCODE lzo
	,storg_lctn VARCHAR(100)   ENCODE lzo
	,mtrl_avblty_dt DATE   ENCODE az64
	,gds_issd_dt DATE   ENCODE az64
	,hdr_cln_dt DATE   ENCODE az64
	,itm_cln_dt DATE   ENCODE az64
	,hld_flg VARCHAR(5)   ENCODE lzo
	,hld_cd VARCHAR(50)   ENCODE lzo
	,hld_cgy VARCHAR(50)   ENCODE lzo
	,hld_stts_dn VARCHAR(100)   ENCODE lzo
	,inrn_stts_dn VARCHAR(100)   ENCODE lzo
	,prtl_dlvry_allwd_cd VARCHAR(50)   ENCODE lzo
	,dbn_cntr_cd VARCHAR(50)   ENCODE lzo
	,dlvry_cmplt_ind VARCHAR(5)   ENCODE lzo
	,ord_prio VARCHAR(100)   ENCODE lzo
	,dlvry_prio VARCHAR(100)   ENCODE lzo
	,fctry_shp_dt DATE   ENCODE az64
	,allctn_typ VARCHAR(50)   ENCODE lzo
	,stndaln_flg VARCHAR(5)   ENCODE lzo
	,refurb_pn_flg VARCHAR(5)   ENCODE lzo
	,aruba_om_flg VARCHAR(5)   ENCODE lzo
	,rgnl_byr VARCHAR(100)   ENCODE lzo
	,hit_flg VARCHAR(5)   ENCODE lzo
	,hit_flfld_flg VARCHAR(5)   ENCODE lzo
	,dc_flfld_flg VARCHAR(5)   ENCODE lzo
	,dc_prmry_flfld_flg VARCHAR(5)   ENCODE lzo
	,cln_ord_stts VARCHAR(100)   ENCODE lzo
	,dmnd_cgy VARCHAR(100)   ENCODE lzo
	,dmnd_typ VARCHAR(100)   ENCODE lzo
	,dmnd_sub_typ VARCHAR(100)   ENCODE lzo
	,cust_bcklg_flg VARCHAR(5)   ENCODE lzo
	,flflm_bcklg_flg VARCHAR(5)   ENCODE lzo
	,flflm_bcklg_prmry_dc_flg VARCHAR(5)   ENCODE lzo
	,cust_bcklg_soli VARCHAR(50)   ENCODE lzo
	,flflm_bcklg_soli VARCHAR(50)   ENCODE lzo
	,flflm_src_sys_nm VARCHAR(50)   ENCODE lzo
	,flflm_plnt_cd VARCHAR(50)   ENCODE lzo
	,flflm_plnt_nm VARCHAR(75)   ENCODE lzo
	,flflm_plnt_cgy VARCHAR(50)   ENCODE lzo
	,prtl_dlvry_flg VARCHAR(5)   ENCODE lzo
	,po_trkg_nr VARCHAR(50)   ENCODE lzo
	,lnkd_po_typ VARCHAR(50)   ENCODE lzo
	,lnkd_po_id VARCHAR(50)   ENCODE lzo
	,mnl_ab_dt DATE   ENCODE az64
	,e2e_seq_iss_flg VARCHAR(5)   ENCODE lzo
	,bcklg_stts_dn VARCHAR(100)   ENCODE lzo
	,explct_futr_flg VARCHAR(5)   ENCODE lzo
	,implct_futr_flg VARCHAR(5)   ENCODE lzo
	,bettr_tgthr_flg VARCHAR(5)   ENCODE lzo
	,mixd_dcmt_flg VARCHAR(5)   ENCODE lzo
	,grp_dcmt_cnt INTEGER   ENCODE az64
	,dc_flg VARCHAR(5)   ENCODE lzo
	,cc_flg VARCHAR(5)   ENCODE lzo
	,ic_flg VARCHAR(5)   ENCODE lzo
	,mfrg_flg VARCHAR(5)   ENCODE lzo
	,cdcfi_flg VARCHAR(5)   ENCODE lzo
	,icpo_flg VARCHAR(5)   ENCODE lzo
	,grp_id VARCHAR(50)   ENCODE lzo
	,dcmt_ky VARCHAR(50)   ENCODE lzo
	,ld_jb_nm VARCHAR(105)   ENCODE lzo
	,rnk INTEGER   ENCODE az64
	,extrc_utc_ts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,is_current_flg VARCHAR(5)   ENCODE lzo
	,futr_typ VARCHAR(50)   ENCODE lzo
	,anpb_grs VARCHAR(300)   ENCODE lzo
	,anpb_rdctn VARCHAR(300)   ENCODE lzo
	,anpb_adjmt VARCHAR(300)   ENCODE lzo
	,antb_grs VARCHAR(300)   ENCODE lzo
	,antb_rdctn VARCHAR(300)   ENCODE lzo
	,antb_adjmt VARCHAR(300)   ENCODE lzo
	,rptg_eg_vs_aup_diff NUMERIC(28,4)   ENCODE az64
	,cust_bcklg_dcmt_crt_dt DATE   ENCODE az64
	,cust_bcklg_dcmt_typ VARCHAR(50)   ENCODE lzo
	,cust_bcklg_dcmt_id VARCHAR(50)   ENCODE lzo
	,cust_bcklg_dcmt_ln_itm VARCHAR(50)   ENCODE lzo
	,cust_bcklg_src_sys_nm VARCHAR(50)   ENCODE lzo
	,flflm_dcmt_crt_dt DATE   ENCODE az64
	,flflm_dcmt_typ VARCHAR(50)   ENCODE lzo
	,flflm_dcmt_id VARCHAR(50)   ENCODE lzo
	,flflm_dcmt_ln_itm VARCHAR(50)   ENCODE lzo
	,flflm_plnt_cgy_dn VARCHAR(100)   ENCODE lzo
	,flflm_dcmt_src VARCHAR(50)   ENCODE lzo
	,prs_nm VARCHAR(300)   ENCODE lzo
	,flflm_opn_qty INTEGER   ENCODE az64
	,flflm_stts VARCHAR(50)   ENCODE lzo
	,eg_exst VARCHAR(50)   ENCODE lzo
	,prdn_ord_nr VARCHAR(50)   ENCODE lzo
	,plnd_ord_nr VARCHAR(50)   ENCODE lzo
	,rls_to_flflm_dt DATE   ENCODE az64
	,rte_cd VARCHAR(50)   ENCODE lzo
	,prt_nr VARCHAR(50)   ENCODE lzo
	,hld_cgy_lvl_1 VARCHAR(100)   ENCODE lzo
	,hld_cgy_lvl_2 VARCHAR(100)   ENCODE lzo
	,hld_mp VARCHAR(50)   ENCODE lzo
	,eg_nt_unt_amt NUMERIC(28,4)   ENCODE az64
	,indt_ctry_cd VARCHAR(10)   ENCODE lzo
	,cbn VARCHAR(100)   ENCODE lzo
	,estmd_shp_dt DATE   ENCODE az64
	,estmd_shp_age_dys BIGINT   ENCODE az64
	,grnlk_flg VARCHAR(5)   ENCODE lzo
	,sply_chn_bcklg_cgy VARCHAR(300)   ENCODE lzo
	,sply_chn_bcklg_cgy_rsn VARCHAR(5000)   ENCODE lzo
	,rvn_hdr VARCHAR(50)   ENCODE lzo
	,mtrl_avblty_age_dys BIGINT   ENCODE az64
	,rptg_aup_amt NUMERIC(28,4)   ENCODE az64
	,rptg_aup_dtrmn VARCHAR(30)   ENCODE lzo
	,flflm_mtrl_avblty_dt DATE   ENCODE az64
	,sab_ctoff_dt DATE   ENCODE az64
	,refresh_dt DATE   ENCODE az64
	,ins_utc_ts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,upd_utc_ts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,pod_rlvnt_flg VARCHAR(10)   ENCODE lzo
	,blng_blck_hdr_cd VARCHAR(250)   ENCODE lzo
	,blng_blck_itm_cd VARCHAR(250)   ENCODE lzo
	,mtrl_avblty_age_bckt VARCHAR(250)   ENCODE lzo
	,estmd_shp_age_bckt VARCHAR(250)   ENCODE lzo
	,dcmt_age_bckt VARCHAR(250)   ENCODE lzo
	,oprnl_bcklg_flg VARCHAR(5)   ENCODE lzo
	,actv_snpsht_flg VARCHAR(5)   ENCODE lzo
	,vrsn_nr INTEGER   ENCODE az64
	,rvn_bcklg_in_qtr_flg VARCHAR(5)   ENCODE lzo
	,clnt_id VARCHAR(5)   ENCODE lzo
	,rvn_futr_out_qtr_flg VARCHAR(5)   ENCODE lzo
	,bkd_past_sab_dt_flg VARCHAR(5)   ENCODE lzo
	,source_nm VARCHAR(200)   ENCODE lzo
	,created_by VARCHAR(100)   ENCODE lzo
	,create_dt TIMESTAMP WITHOUT TIME ZONE  DEFAULT ('now'::character varying)::timestamp without time zone ENCODE az64
	,batch_run_dt TIMESTAMP WITHOUT TIME ZONE  DEFAULT ('now'::character varying)::timestamp without time zone ENCODE az64
	,lt_prt_nr VARCHAR(40)   ENCODE lzo
	,lt_flg VARCHAR(1)   ENCODE lzo
	,rptg_aup_unt_amt NUMERIC(28,4)   ENCODE az64
	,rptg_eg_nt_unt_amt NUMERIC(28,4)   ENCODE az64
	,dcmt_ldg_dt DATE   ENCODE az64
	,sto_dlvry_note_ttl_qty INTEGER   ENCODE az64
	,sto_dlvry_note_opn_qty INTEGER   ENCODE az64
	,sto_gds_issd_ttl_qty INTEGER   ENCODE az64
	,sto_gds_issd_opn_qty INTEGER   ENCODE az64
	,sto_gds_rcpt_ttl_qty INTEGER   ENCODE az64
	,sto_gds_rcpt_opn_qty INTEGER   ENCODE az64
	,plnd_cust_dlvry_dt DATE   ENCODE az64
	,plnd_cust_shp_dt DATE   ENCODE az64
	,flflm_hld_flg VARCHAR(4)   ENCODE lzo
	,flflm_hld_typ VARCHAR(50)   ENCODE lzo
	,sls_ofc_sto_crt_dt DATE   ENCODE az64
	,sls_ofc_sto_typ VARCHAR(9)   ENCODE lzo
	,sls_ofc_sto_id VARCHAR(50)   ENCODE lzo
	,sls_ofc_sto_ln_itm VARCHAR(20)   ENCODE lzo
	,sls_ofc_sto_hld_flg VARCHAR(4)   ENCODE lzo
	,sls_ofc_sto_hld_typ VARCHAR(50)   ENCODE lzo
	,cc_sto_crt_dt DATE   ENCODE az64
	,cc_sto_typ VARCHAR(9)   ENCODE lzo
	,cc_sto_id VARCHAR(50)   ENCODE lzo
	,cc_sto_ln_itm VARCHAR(20)   ENCODE lzo
	,cc_sto_hld_flg VARCHAR(4)   ENCODE lzo
	,cc_sto_hld_typ VARCHAR(50)   ENCODE lzo
	,rbllr_sto_crt_dt DATE   ENCODE az64
	,rbllr_sto_typ VARCHAR(9)   ENCODE lzo
	,rbllr_sto_id VARCHAR(50)   ENCODE lzo
	,rbllr_sto_ln_itm VARCHAR(20)   ENCODE lzo
	,rbllr_sto_hld_flg VARCHAR(4)   ENCODE lzo
	,rbllr_sto_hld_typ VARCHAR(50)   ENCODE lzo
	,hit_sto_crt_dt DATE   ENCODE az64
	,hit_sto_typ VARCHAR(9)   ENCODE lzo
	,hit_sto_id VARCHAR(50)   ENCODE lzo
	,hit_sto_ln_itm VARCHAR(20)   ENCODE lzo
	,hit_sto_hld_flg VARCHAR(4)   ENCODE lzo
	,hit_sto_hld_typ VARCHAR(50)   ENCODE lzo
	,refresh_rgn VARCHAR(25)   ENCODE lzo
	,rvn_bcklg_flg VARCHAR(4)   ENCODE lzo
	,rptg_prod_fmly VARCHAR(200)   ENCODE lzo
	,prod_lc_stts VARCHAR(50)   ENCODE lzo
	,opty_id VARCHAR(50)   ENCODE lzo
	,rptg_bs_prod VARCHAR(50)   ENCODE lzo
	,bs_prod VARCHAR(50)   ENCODE lzo
	,rptg_hld_flg VARCHAR(2)   ENCODE lzo
	,rptg_hld_cd VARCHAR(10)   ENCODE lzo
	,rptg_hld_cgy VARCHAR(100)   ENCODE lzo
	,rptg_hld_cgy_lvl_1 VARCHAR(100)   ENCODE lzo
	,rptg_hld_cgy_lvl_2 VARCHAR(100)   ENCODE lzo
	,rptg_hld_mp VARCHAR(10)   ENCODE lzo
	,rte_to_mkt VARCHAR(25)   ENCODE lzo
	,prod_lcns_flg VARCHAR(1)  DEFAULT 'N'::character varying ENCODE lzo
	,uncln_age_dys INTEGER  DEFAULT 0 ENCODE az64
	,sca_sls_geo VARCHAR(50)   ENCODE lzo
	,sls_geo VARCHAR(50)   ENCODE lzo
	,sls_sub_geo VARCHAR(50)   ENCODE lzo
	,sls_geo_ctry_cd VARCHAR(3)   ENCODE lzo
	,sls_geo_ctry_nm VARCHAR(50)   ENCODE lzo
	,fctry_mrgn_ttl_usd_amt NUMERIC(18,4)   ENCODE az64
	,esc_ttl_usd_amt NUMERIC(18,4)   ENCODE az64
	,rte_dys SMALLINT   ENCODE az64
	,futr_cgy VARCHAR(10)   ENCODE lzo
	,drvd_cust_rqstd_shp_dt DATE   ENCODE az64
)
DISTSTYLE AUTO
 SORTKEY (
	src_sys_rgn
	)
;
ALTER TABLE published.dly_cust_flflm_bcklg_snapshot_nrt owner to arubauser;
